services:
  nginx:
    image: nginx:alpine
    container_name: loar-nginx
    ports:
      - "80:80" 
      - "443:443" 
    volumes:
      - ./nginx.simple.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/web/dist:/usr/share/nginx/html:ro
    depends_on:
      - app-server
    restart: unless-stopped
    networks:
      - loar-network

  app-server:
    image: oven/bun:1.1.8
    container_name: loar-server
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/loar-fullstack
      - CORS_ORIGIN=https://loartech.xyz
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-defaultsecret}
      - BETTER_AUTH_URL=https://loartech.xyz
      - LUMAAI_API_KEY=${LUMAAI_API_KEY}
      - KLING_API_KEY=${KLING_API_KEY}
      - KLING_ACCESS_KEY=${KLING_ACCESS_KEY}
      - KLING_SECRET_KEY=${KLING_SECRET_KEY}
      - WALRUS_PUBLISHER_URL=${WALRUS_PUBLISHER_URL:-https://publisher.walrus.xyz}
      - WALRUS_AGGREGATOR_URL=${WALRUS_AGGREGATOR_URL:-https://aggregator.walrus.xyz}
    command: ["sh", "-c", "apt-get update && apt-get install -y curl && echo 'Building frontend...' && cd apps/web && rm -rf node_modules bun.lockb && bun install --no-cache && bun run build && echo 'Frontend built, starting server...' && cd ../server && bun add drizzle-kit && bun run db:push && echo 'Starting server...' && (test -f dist/index.js && bun run dist/index.js || bun run src/index.ts)"]
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - loar-network
    ports:
      - "3005:3000"

  postgres:
    image: postgres:15
    container_name: loar-postgres
    environment:
      POSTGRES_DB: loar-fullstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - loar-network

volumes:
  postgres_data:

networks:
  loar-network:
    driver: bridge
