services:
  nginx:
    image: nginx:alpine
    container_name: loar-nginx
    ports:
      - "8080:80"  # remapped host port from 80 → 8080
    volumes:
      - ./nginx.simple.conf:/etc/nginx/nginx.conf:ro
      - ./apps/web/dist:/usr/share/nginx/html:ro
    depends_on:
      - app-server
    restart: unless-stopped
    networks:
      - loar-network

  app-server:
    image: oven/bun:1.1.8-alpine
    container_name: loar-server
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/loar-fullstack
      - CORS_ORIGIN=http://178.156.142.77
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-defaultsecret}
      - BETTER_AUTH_URL=http://178.156.142.77
    command: ["sh", "-c", "apk add --no-cache curl && bun run db:push && bun run apps/server/dist/index.js"]
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - loar-network
    ports:
      - "3005:3000"  # remapped host port from 3000 → 3005

  postgres:
    image: postgres:15
    container_name: loar-postgres
    environment:
      POSTGRES_DB: loar-fullstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # optional: remap host port if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - loar-network

volumes:
  postgres_data:

networks:
  loar-network:
    driver: bridge
