[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version="0.8.30"
optimizer=true
optimizer_runs=750
via_ir=false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
#mainnet = "${RPC_1}"
#sepolia = "${RPC_11155111}"

[fmt]
line_length = 100

[etherscan]
# Chain-specific API keys using standardized environment variables
# Format: VERIFICATION_KEY_{chainId}
# mainnet = { key = "${VERIFICATION_KEY_1}" }
# arbitrum = { key = "${VERIFICATION_KEY_42161}" }
# base = { key = "${VERIFICATION_KEY_8453}" }
